// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUor7Q4RXpJcIudNW3LY_1CiIHfKujZXE',
    appId: '1:128490328932:web:fc757d21409abedfb9e071',
    messagingSenderId: '128490328932',
    projectId: 'chatapp-c7e11',
    authDomain: 'chatapp-c7e11.firebaseapp.com',
    storageBucket: 'chatapp-c7e11.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq0nvPZk0fOo2fntbJTR3GJXVSYsaxBMU',
    appId: '1:128490328932:android:7712ab8d89ffdc54b9e071',
    messagingSenderId: '128490328932',
    projectId: 'chatapp-c7e11',
    storageBucket: 'chatapp-c7e11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfr828vtncnzZBSouMTxsp_W2LDL7l6C0',
    appId: '1:128490328932:ios:5d01d84b7547fa8cb9e071',
    messagingSenderId: '128490328932',
    projectId: 'chatapp-c7e11',
    storageBucket: 'chatapp-c7e11.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfr828vtncnzZBSouMTxsp_W2LDL7l6C0',
    appId: '1:128490328932:ios:5d01d84b7547fa8cb9e071',
    messagingSenderId: '128490328932',
    projectId: 'chatapp-c7e11',
    storageBucket: 'chatapp-c7e11.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
